spring.application.name=Clinica Universitaria

spring.datasource.url=jdbc:mysql://localhost:3306/clinica_universitaria?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true

mercado.pago.access-token=APP_USR-8427692382586379-070322-4a7dcd5ded55030d5dd73e2423775b49-3516258843
mercado.pago.public-key=APP_USR-ccfc2f73-1b3e-4e40-8c11-b28ab53bfdcd
mercado.pago.success-url=http://localhost:8080/pagos/exito
mercado.pago.failure-url=http://localhost:8080/pagos/fallo
mercado.pago.pending-url=http://localhost:8080/pagos/pendiente

server.port=8080
